# This is a basic workflow to help you get started with Actions

name: Data Sharing between jobs

# Controls when the workflow will run
on: [push]

jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
      - run:
         cal 2022 > cal.txt
       
