# This is a basic workflow to help you get started with Actions

name: Data Sharing between jobs

# Controls when the workflow will run
on: [push]

jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
      - run:
         expr 3 + 7 > cal.txt
       
  job2:
    runs-on: windows-latest
  job3:
    runs-on: macOS-latest
