# This is a basic workflow to help you get started with Actions

name: Data Sharing between jobs

# Controls when the workflow will run
on: [push]

jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
      - run:
         expr 3 + 7 > cal.txt
       - name: Upload the cal.txt file
         uses: actions/upload-artifact@v3
         with:
           name: calendar
           path: calendar.txt

  job2:
    name: Dowload file
    Needs: [job1]
    runs-on: windows-latest
    steps:
       - name: Download the cal.txt file
         uses: actions/download-artifact@v3
         with:
           name: calendar
           path: calendar.txt
    
  job3:
    runs-on: macOS-latest
