# Understand user defined variables

name: User Defined Variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
     firstName: joanne
     lastName: jones

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 windows-job:
  runs-on: windows-latest
  steps:
   - name: Display First Name Variable
     run: echo "Hi ${{env.firstName}}"
   - name: Display Last Name Variable 
     run: echo "Hi ${{env.lastName}}"
   - name: Display Job
     run: echo ${{job}}
     env:
      job: "Developer"
      
 ubuntu-job:
  runs-on:
     ubuntu-latest
  steps:
  - name: Display env variables
    run: echo "Hi ${{env.lastName}}"


 
