# Understand user defined variables

name: User Defined Variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
     firstName: joanne
     lastName: jones

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 windows-job:
  runs-on:
     windows-latest
  steps:
     - run: echo "Hi ${{env.firstName}}"
     - run: echo "Hi ${{env.lastName}}"
     - run: ${{env.firstName}} having {{job}}
         
 ubuntu-job:
  runs-on:
     ubuntu-latest
  steps:
  - name: Display env variables
    run: echo "Hi ${{env.lastName}}"


 
